{% set version = "3.0.0" %}
{% set filename = "apache-arrow-" + version + ".tar.gz" %}
{% set checksum = "73c2cc3be537aa1f3fd9490cfec185714168c9bfd599d23e287ab0cc0558e27a" %}

package:
  name: arrow-cpp
  version: {{ version }}

source:
  fn: {{ filename }}
  url: https://dist.apache.org/repos/dist/release/arrow/arrow-{{ version }}/{{ filename }}
  sha256: {{ checksum }}

build:
  number: 1
  run_exports:
    - {{ pin_subpackage("arrow-cpp", max_pin="x.x.x") }}
  ignore_run_exports:
    - grpc-cpp
    - libprotobuf
    - libevent {{ libevent }}
    - re2
    - glog
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - grpc-cpp {{ grpc_cpp }}
    - cmake 3.19   # to avoid https://gitlab.kitware.com/cmake/cmake/-/issues/18810
    - autoconf
    - ninja
    - make
    - utf8proc
    - libboost {{ boost }}
    - thrift-cpp >=0.13
    - abseil-cpp {{ abseil_cpp }}
    - libprotobuf {{ protobuf }}
  host:
    - aws-sdk-cpp
    - abseil-cpp
    - boost-cpp {{ boost }}
    - brotli
    - bzip2
    - c-ares
    - double-conversion
    - flatbuffers
    - gflags
    - glog
    - grpc-cpp {{ grpc_cpp }}
    - libprotobuf {{ protobuf }}
    - lz4-c
    - numpy {{ numpy }}
    - orc
    - rapidjson
    - re2
    - snappy
    - thrift-cpp >=0.13
    - uriparser
    - zlib {{ zlib }}
    - zstd
    - utf8proc
    - openssl
    - libevent {{ libevent }}
    - python {{ python }}
  run:
    - {{ pin_compatible('numpy', lower_bound='1.11') }}
    - boost-cpp {{ boost }}
    - brotli
    - c-ares
    - double-conversion
    - gflags
    - glog
    - grpc-cpp {{ grpc_cpp }}
    - lz4-c
    - libboost
    - libprotobuf {{ protobuf }}
    - openssl
    - python {{ python }}
    - re2
    - snappy
    - utf8proc
    - uriparser
    - zlib    # handled by run exports
    - zstd

test:
  commands:
    # headers
    - test -f $PREFIX/include/arrow/api.h
    - test -f $PREFIX/include/arrow/flight/types.h
    - test -f $PREFIX/include/plasma/client.h
    - test -f $PREFIX/include/parquet/api/reader.h

    # shared
    - test -f $PREFIX/lib/libarrow${SHLIB_EXT}
    - test -f $PREFIX/lib/libarrow_dataset${SHLIB_EXT}
    - test -f $PREFIX/lib/libarrow_flight${SHLIB_EXT}
    - test -f $PREFIX/lib/libarrow_python${SHLIB_EXT}
    - test -f $PREFIX/lib/libparquet${SHLIB_EXT}
    - test -f $PREFIX/lib/libplasma${SHLIB_EXT}
    # absence of static libraries
    - test ! -f $PREFIX/lib/libarrow.a
    - test ! -f $PREFIX/lib/libarrow_flight.a
    - test ! -f $PREFIX/lib/libarrow_python.a
    - test ! -f $PREFIX/lib/libplasma.a
    - test ! -f $PREFIX/lib/libparquet.a

    # conda tools
    - conda inspect linkages -p $PREFIX $PKG_NAME

about:
  home: http://github.com/apache/arrow
  license: Apache 2.0
  license_file: LICENSE.txt
  summary: 'C++ libraries for Apache Arrow'

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
