{% set version = "3.0.0" %}
{% set filename = "apache-arrow-" + version + ".tar.gz" %}
{% set checksum = "73c2cc3be537aa1f3fd9490cfec185714168c9bfd599d23e287ab0cc0558e27a" %}

package:
  name: pyarrow-base
  version: {{ version }}

source:
  fn: {{ filename }}
  url: https://dist.apache.org/repos/dist/release/arrow/arrow-{{ version }}/{{ filename }}
  sha256: {{ checksum }}

build:
  number: 3
  string: {{ build_type }}_py{{ python | replace(".", "") }}_{{ PKG_BUILDNUM }}
  ignore_run_exports:
    - glog
    - snappy
    - grpc-cpp
    - cudatoolkit
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - make
  host:
    # directly pin boost-cpp as we also seem to directly include boost symbols
    # in the Python modules.
    - boost-cpp {{ boost }}
    - {{ pin_compatible('arrow-cpp', exact=True) }}
    - cython
    - grpc-cpp {{ grpc_cpp }}
    - numpy {{ numpy }}
    - python {{ python }}
    - setuptools {{ setuptools }}
    - setuptools_scm 5.0.2
    - setuptools-scm 5.0.2
    - six {{ six }}
    - uriparser

  run:
    - {{ pin_compatible('arrow-cpp', exact=True) }}
    - {{ pin_compatible('numpy', lower_bound='1.16') }}
    - _arrow_select {{ arrow_select_version }}
    - boost-cpp {{ boost }}
    - glog
    - pandas
    - python {{ python }}
    - six {{ six }}
    - snappy
    - gflags
  run_constrained:
    - cudatoolkit >=10.2  # [build_type == 'cuda']

test:
  imports:
    - pyarrow
    - pyarrow.dataset
    - pyarrow.flight
    - pyarrow.orc
    - pyarrow.parquet
    - pyarrow.plasma
    - pyarrow.fs
    - pyarrow._s3fs
    - pyarrow._hdfs
    - pyarrow.cuda   # [build_type == 'cuda']
  commands:
    - test ! -f ${SP_DIR}/pyarrow/tests/test_array.py

about:
  home: http://github.com/apache/arrow
  license: Apache 2.0
  license_file: LICENSE.txt
  summary: 'Python libraries for Apache Arrow'

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
